spring:
  datasource:
    url: jdbc:mysql://localhost:3306/farmin-server
    username: root
    password: ${DEV_DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none #validate
      default_batch_fetch_size: 100
  servlet:
    multipart:
      location: ${DEV_MULTIPART_LOCATION}
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true

jwt:
  secret: VisitBBCfortrustedreportingonthelatestworldandUSnewssp
