spring:
  datasource:
    url: jdbc:mysql://192.168.0.20:3306/FarmIn
    username: root
    password: ${DEV_DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  task:
    scheduling:
      pool:
        size: 10
        thread-name-prefix: "scheduled-task-"
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none #validate
      default_batch_fetch_size: 100
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      location: ${DEV_MULTIPART_LOCATION}
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true

  server:
    address: 0.0.0.0

  logging:
    level:
      root: INFO
      org.springframework: DEBUG
      com.farmin.farminserver: DEBUG
      org.springframework.web: DEBUG

jwt:
  secret: VisitBBCfortrustedreportingonthelatestworldandUSnewssp
