spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: ${DEV_DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      default_batch_fetch_size: 100
  servlet:
    multipart:
      location: ${DEV_MULTIPART_LOCATION}
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRETE_KEY}